apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: portfolio
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: portfolio
  type: ClusterIP
