name: CI

on:
  push:
    branches:
      - main
    path-ignore:
      - "k8s/**"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:${{ github.run_id }}

  update-newtag-in-helm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.TOKEN}}

      - name: Set up Helm
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/portfolio-chart/values.yaml

      - name: Commit new tag
        run: |
          git config --global user.email "jatinkumar10082003@gmail.com"
          git config --global user.name "Jatin Kumar"
          git add helm/portfolio-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
